services:
  free_games_bot:
    build: .
    container_name: free_games_bot
    logging:
      driver: json-file
    env_file:
      - .env
    command: ["./entrypoint.sh"]
    volumes:
      - ./storage:/app/storage